### ISSUE TITLE
USER STORY: Follow/Unfollow and followed feed.

### ISSUE THREAD

**Issue by jindah** [jindah/picagram#10]
**As a registered user, I want to manage my interaction with other profiles and have a personalized feed, so that I can curate my content experience.**

### Acceptance Criteria

**Follow/Unfollow Feature:**
- A registered user should find a 'follow' button on all profiles not followed. Clicking the button changes its appearance and name to 'unfollow'.
- When a user clicks follow:
  - Their following count should increase by 1.
  - The profile they followed should have its follower count increased by 1.
  - The button should change.
- When a user clicks unfollow:
  - Their following count should decrease by 1.
  - The profile they unfollowed should have its follower count decreased by 1.
  - The button should change.

**Feed Navigation:**
- In the main feed navigation bar, the user can easily locate and navigate to the 'feed' tab.

**Personalized Feed:**
- The feed should display posts only from users the current user is following.

### Tasks

- [x] Design and implement the Follow/Unfollow button site-wide on all profile instances.
- [x] Implement logic to change the button from 'follow' to 'unfollow' and back.
- [x] Implement logic to update the count of both accounts involved in the 'follow'.
- [x] Implement logic to update both accounts involved in the 'unfollow'.
- [x] Ensure 'feed' is available in the feed navigation bar.
- [x] Implement logic to display only posts by users the user follows.
- [x] Thoroughly test the working functionality of the follow/unfollow feature and personalized feed.
