### ISSUE TITLE
USER STORY: Profile Pages

### ISSUE THREAD

**Issue by jindah** [jindah/picagram#12]
**As a registered user, I can click a user's avatar to visit their profile to see their information and posts.**

### Acceptance Criteria

- **Avatars:**
The avatars site-wide should be clickable links leading to the relevant profile details page.

- **Profiles:**
Every user will have a profile page displaying all relevant information. This includes their profile card and, beneath it, a list of all posts by the user instance.

### Tasks

- [x] Implement avatars as a link to the relevant user profile instance.
- [x] Design the UI for the profile card, including the following information:
  - Avatar
  - Name
  - Joined date
  - Number of posts
  - Number of followers
  - Number of following
  - Follow/Unfollow button
- [x] Implement a post list below the profile card, showing only the posts from the profile instance.
- [x] Implement infinite scroll functionality.
