### ISSUE TITLE
USER STORY: User Profile / Update User Profile

### ISSUE THREAD

**Issue by jindah** [jindah/picagram#13]
**As a registered user, I want to manage my profile, including viewing, updating, and deleting content and information.**

### Acceptance Criteria

- **Profile Navigation:**
A logged-in user can easily navigate to their profile page from the navbar link.

- **Edit/Delete Options:**
The owner of the profile and posts can see an icon on all posts and profiles they own. Once clicked, they can choose the update or delete options.

- **Update Profile Option:**
When the user is on the profile page they own, the options menu icon is visible. When clicked, they can update their profile information and profile image. The updated information is reflected upon submission.

**Tasks**
- [x] Ensure logged-in users have easy access to their personal profile page.
- [x] Implement the options icon menu on all posts they own, including posts on the profile page and their profile information card.
- [x] Implement ability to update username and password.
- [x] The delete option should always trigger a 'delete confirmation' modal.
- [x] Implement the options menu on the profile page for the owner of the profile instance.
- [x] Ensure data is updated when users submit their updates.
- [x] Redirect the user back to the profile page after updating.
