### ISSUE TITLE
USER STORY: Most Followed Profiles

### ISSUE THREAD

**Issue by jindah** [jindah/picagram#14]
**As a registered user, I can view the list of 'Most Followed' accounts so that I can discover popular profiles.**

### Acceptance Criteria

- **Top Page:**
A top page can be navigated to where users can see a list of the most followed accounts.

- **Profiles:**
Each profile in the list displays necessary information and follow buttons, enabling other users to select from the list or follow the profile instance.

### Tasks

- [x] Design the UI for the 'Most Followed' page.
- [x] Design and implement each profile card with the relevant information and follow button.
- [x] Implement the infinite scroll functionality for the list.
