### ISSUE TITLE
USER STORY: Most Liked Posts

### ISSUE THREAD

**Issue by jindah** [jindah/picagram#16]
**As a user, I want to view the "most liked" posts so that I can engage with it.**

### Acceptance Criteria

- **Most Liked Component:**
All users should see a 'Most Liked' component on all feed pages, showcasing the most liked posts.

- **Posts:**
Each post within the section should be clickable, redirecting the user to the post details page.

### Tasks

- [ ] Design and implement the UI for the 'Most Liked' component.
- [ ] Ensure the component is visible on every feed page.
- [ ] Display necessary information regarding each post in the preview within the component.
- [ ] Implement the functionality that redirects the user to the post details page upon clicking a post in the 'Most Liked' section.

**Comment by jindah** [comment]
No need for this with feed and liked pages.
