### ISSUE TITLE
USER STORY: Comments

### ISSUE THREAD

**Issue by jindah** [jindah/picagram#17]
**As a user, I want to actively participate in discussions by commenting on posts. Additionally, as a non-registered user, I want to read comments to follow the conversation.**

### Acceptance Criteria

- **Commenting (Registered User):**
Below each post details card and above the comments, a registered user should have the capability to write comments and post them to the comments section.
Comments owned by the current user should have options to be edited or deleted.
The latest comment should be prominently displayed at the top of the comments.

- **Viewing Comments (Non-registered User):**
Users, whether registered or not, should be able to scroll down below the post details to find the comment section.
Each comment should display the commenter's username, avatar, created date, and content.

### Tasks

**Commenting (Registered User):**
- [x] Create the comment form with a simple content text field and a post button.
- [x] Implement the logic to post the comment, ensuring it appears at the top of the comments list.
- [x] Ensure relevant information is visible on each comment instance: avatar, name, date of comment, content.
- [x] Implement icons for editing and deleting comments.
- [x] Test the comment deletion and editing functionality on both the site and database.

**Viewing Comments (Non-registered User):**
- [x] Develop a comments section component.
- [x] Implement the comments section beneath the post details.
- [x] Include the correct profile information for each individual comment.
