### ISSUE TITLE
USER STORY: Search Bar

### ISSUE THREAD

**Issue by jindah** [jindah/picagram#18]
**As a user, I can search each accessible feed to filter the lists of posts.**

### Acceptance Criteria

- **Search Bar:**
The search bar should be visibly located at the top of all feed pages, easily accessible.

- **Searchable Fields:**
The search bar should search relevant fields on each page. For example, on the feed or home page, where all posts exist, it should search the publisher name and content.

### Tasks

- [x] Design the UI for the search bar.
- [x] Implement the search bar above the list of posts on each feed page.
- [x] Implement the logic behind the search bar; review searchable fields for each feed according to the acceptance criteria.
  - [x] Home
  - [x] Feed
  - [x] Liked
  - [x] Top
