### ISSUE TITLE
USER STORY: Notifications

### ISSUE THREAD

**Issue by jindah** [jindah/picagram#26]
As a user, I want to be able to read notifications so that I can stay informed about interactions with my posts, such as likes or comments. 

### Acceptance Criteria
 - The user can see new notifications in the notification inbox.
-  The user can mark notifications as read.

### Tasks

- [x]  Create necessary models and serializers
- [x]  Create notification page and notification component
- [x]  Retrieve notifications from API and list them on notification page
- [x]  Display notifications as read or unread depending on is_read status
