### ISSUE TITLE
USER STORY: Deploy Backend

### ISSUE THREAD

**Issue by jindah** [jindah/picagram#3]
As **the developer** I want to **deploy the backend to Heroku** so that **it is accessible and functional on the web.**

### Acceptance Criteria

- **API Functionailty:**
The API appears and functions with correct functionality as seen in the local version. Running without any errors or issues.

- **Accessibility:**
The application is accessible via the Heroku URL.

### Tasks
- [x]  Create ElephantSQL database
- [x]  Create Heroku APP, add applicable config-vars
- [x]  Deploy App
- [x]  Check urls work as expected

**Comment by jindah** [comment]
I had problem with HEROKU givning an error:

2023-12-28T12:53:34.105704+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=picagram-ac5efc799683.herokuapp.com request_id=68594edf-d29d-46f1-93ab-555c5dc99343 fwd="217.213.102.166" dyno= connect= service= status=503 bytes= protocol=https

The Heroku error code H10 indicates that your application has crashed. 

The reason to this found to be my Procfile had wrong web: gunicorn your_project_name.wsgi line.
