### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by jindah** [jindah/picagram#4]
As a user, I can effortlessly navigate through the site so that my overall experience is frustration-free.

### Acceptance Criteria
- **Logo:**
The main Navbar includes a logo to identify the site easily. It should be clickable as the main home link.

- **Navigation Links:**
- For unregistered or non-logged-in users: Display 'Sign Up' and 'Login' links.
- For logged-in users: Display 'Add Post,' 'Feed,' 'Liked,' and 'Sign Out' links.

- **Signup**
The signup button should be bright and easily findable to attract new users.

### Tasks
- [ ] Create the Navbar component

- [ ] Link all links to necessary pages and wire up connections in app.js
- [ ] Add 'sign up' and 'login' links for unregistered or non-logged-in users
- [ ] Add "Add Post, Feed, Liked and Sign out" for inlogged users
