### ISSUE TITLE
USER STORY: Sign up / Sign in landing page

### ISSUE THREAD

**Issue by jindah** [jindah/picagram#6]
As a user, I can sign in or sign up for an account so that I can enjoy the benefits of a registered user.

### Acceptance Criteria
- **Landing page:**
When visiting the site, it should be very clear where users can sign in or sign up for a new account.

- **Sign Up Form:**
When clicking the sign-up link, the user should be directed to a simple sign-up form. Upon submitting the form, the user's profile should be created with the provided credentials.

- **Sign up Information:**
During sign-up, a user should provide a username and password, along with a password confirmation field.

### Tasks
- [x]  Design and implement the UI for a sign-in form with a visible button for sign-up on the landing page.
- [x]  Design and create a sign-up form, ensuring to include three inputs:
- username
- password
- password confirmation
- [x]  Create a link to login form for misguided users who are already registered.
- [x]  Redirect users to the login page upon signing up.
