### ISSUE TITLE
USER STORY: Post Page

### ISSUE THREAD

**Issue by jindah** [jindah/picagram#8]
**As a user, I want to be able to select a post, read its content, and engage with it by commenting and liking.**

### Acceptance Criteria

- **Post Details:**
When selecting a post, the user should be directed to the post detail page where they can read its content, like, and comment.

- **Interactive Sections:**
A non-registered user should be able to view the comments count, likes count, and view comments.

### Tasks
- [x] Create a post detail UI component for each post using JSX.
- [x] Use the correct object fields to fill in the post template.
- [x] Implement comment and like count icons under each image.
- [x] Implement the comments section underneath each post detail.
- [x] Implement a edit post button for post owners.
