### ISSUE TITLE
USER STORY: Post Page

### ISSUE THREAD

**Issue by jindah** [jindah/picagram#9]
**As a user, I want to be able to select a post, read its content, and engage with it by commenting and liking.**

### Acceptance Criteria

**Post Details:**
- When selecting a post, the user should be directed to the post detail page where they can read its content, like, and comment.

**Interactive Sections:**
- A non-registered user should be able to view the comments count, likes count, and view comments.

### Tasks

- [ ] Create a post detail UI component for each post using JSX.
- [ ] Use the correct object fields to fill in the post template.
- [ ] Implement comment and like count icons under each image.
- [ ] Implement the comments section underneath each post detail.
- [ ] Implement a button for post owner to edit the post.
